### ISSUE TITLE
It seems like you're escaping things when you don't need to  in .env ?

### ISSUE THREAD

**Issue by simonmcnair** [nck974/self-hosted-vaultwarden-setup#1]
Just curious when I tried to use the guide.  Cheers for the hard work.

https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token

![image](https://github.com/user-attachments/assets/b58e3fe2-90ae-41d1-a1e2-ff21c17216b0)

**Comment by nck974** [comment]
You can checkout why I did it in the history of that page:
https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page/bbc9dcd4a554d4755e0ec5b10ef9f8450974bd65

> How to prevent variable interpolation in docker-compose.yml
> 
> When [using Docker Compose](https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose) and you configure the ADMIN_TOKEN via the environment directive you need to escape all five occurrences of the dollar sign $ in the generated argon2 PHC string using two dollar signs $$ in order to prevent [variable interpolation](https://docs.docker.com/compose/compose-file/#interpolation):
> 
>   environment:
>     ADMIN_TOKEN: $$argon2id$$v=19$$m=19456,t=2,p=1$$UUZxK1FZMkZoRHFQRlVrTXZvS0E3bHpNQW55c2dBN2NORzdsa0Nxd1JhND0$$cUoId+JBUsJutlG4rfDZayExfjq4TCt48aBc9qsc3UI
> 
> This can be done automatically e.g. using sed by adding | sed 's#\$#\$\$#g' to the end of the argon2 command line above.

I'm not sure if this is still needed or not.

**Comment by simonmcnair** [comment]
When I used your example it didn't work.  When I removed the extra escape characters it did work.  IIRC the token changed too
Regards
Simon

**Comment by nck974** [comment]
@simonmcnair I reviewed again the issue. It seems the escaping is only needed when the environment variable is directly in the `docker-compose.yaml`. Once it is saved in the .env is not needed anymore.

I changed it. Thank you for commenting the issue,
